### ISSUE TITLE
Default TTL appears to be ignored when creating an API or app key

### ISSUE THREAD

**Issue by anthonyralston** [rizkybiz/vault-plugin-secrets-datadog#3]
Unless I am missing something (which I may be), it appears as though the `default_ttl` is ignored when creating an API or an app key and the `max_ttl` is used instead. Is there some way to control the TTL of the lease generated?

```
vault write datadog/roles/test \
    app_key_scopes=incident_read,usage_read \
    default_ttl=5m max_ttl=30m

vault read datadog/apikey/test
WARNING! The following warnings were returned from Vault:

  * TTL of "768h" exceeded the effective max_ttl of "30m"; TTL value is capped
  accordingly

Key                Value
---                -----
lease_id           datadog/apikey/test/some-lease-id
lease_duration     30m
lease_renewable    true
api_key            redacted
```

**Comment by rizkybiz** [comment]
That appears to be a documentation error. I'll go ahead and update the README to show `ttl` instead of `default_ttl`. Thanks for the issue!

**Comment by anthonyralston** [comment]
Nice, that looks to have fixed it. Really appreciate the quick response!
